
services:
  
  database:
    image: mysql
    env_file: .env
    container_name: ${CONTAINER_NAME}-database
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DATABASE_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - internal

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin:latest
    env_file: .env
    container_name: ${CONTAINER_NAME}-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - 8081:80
    networks:
      - internal

  wordpress:
    depends_on:
      - database
      - phpmyadmin
    image: wordpress
    env_file: .env
    container_name: ${CONTAINER_NAME}-wordpress
    environment:
      - WORDPRESS_DB_HOST=database:3306
      - WORDPRESS_DB_USER=${DATABASE_USER}
      - WORDPRESS_DB_PASSWORD=${DATABASE_ROOT_PASSWORD}
    restart: unless-stopped
    volumes:
      - './:/var/www/html'
      - ./wp-content:/var/www/html/wp-content
    ports:
      - 8080:80
    networks:
      - internal

volumes:
  db_data:

networks:
  internal:
    driver: bridge